### ISSUE TITLE
Error: Cannot find module 'invariant'

### ISSUE THREAD

**Issue by ajberk** [pivotal-cf/pui-react-tools#10]
When trying to use pui-react-tools on travis CI, we are running into the following error:

```

Error: Cannot find module 'invariant'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/travis/build/SunRun/savings-calculator/node_modules/pui-react-tools/middleware/webpack.js:7:17)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/SunRun/savings-calculator/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Is invariant missing from you package.json?
It would be cool if this didn't happen. 

Thanks!

**Comment by rdy** [comment]
fixed in 1.3.1
