### ISSUE TITLE
problems with define plugin at module level

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#27]
we're implementing feature flagging:

`pui-react-tools.js`
```js
const featureFlagPlugin = new webpack.DefinePlugin({
  FEATURE_FLAGS: {
    prettyCoolFeature: JSON.stringify(true)
  }
});


module.exports = {
  webpack: {
    base: {
      plugins: [
        ...basePlugins,
        featureFlagPlugin
      ]
    },
    test: {
      plugins: [
        ...testPlugins,
        featureFlagPlugin
      ]
    },
    development: {
      plugins: [
        ...devPlugins,
        featureFlagPlugin
      ]
    },
    production: {
      plugins: [
        ...prodPlugins,
        featureFlagPlugin
      ]
  }
};
```

`feature_component.js`
```jsx
if(FEATURE_FLAGS.prettyCoolFeature) {
  function PrettyCoolFeature(props) {
    // prettyCoolFeature
  }
} else {
  function PrettyCoolFeature(props) {
    // oldBoringFeature
  }
}

module.exports = PrettyCoolFeature;
```

when we run build:

```
± ab+at |master {5} S:1 U:3 ✗| → NODE_ENV=production gulp assets
[17:58:21] Using gulpfile ~/workspace/project-name/gulpfile.js
[17:58:21] Starting 'clean-assets'...
[17:58:21] Finished 'clean-assets' after 17 ms
[17:58:21] Starting 'assets'...
[17:58:49] Plumber found unhandled error:
 Error in plugin 'webpack-stream'
Message:
    ./~/babel-loader/lib!./~/pui-react-tools/assets/entry-loader.js?name=index.html!./app/components/application.js
Module build failed: ReferenceError: FEATURE_FLAGS is not defined
    at /Users/pivotal/workspace/project-name/app/components/pretty_cool_feature.js:11:8
    at Object.<anonymous> (/Users/pivotal/workspace/project-name/app/components/pretty_cool_feature.js:72:18)
    at Module._compile (module.js:571:32)
    at loader (/Users/pivotal/workspace/project-name/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/project-name/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
 @ ./app/bootstrap.js 24:4-97
[17:58:49] Version: webpack 1.14.0

ERROR in ./~/babel-loader/lib!./~/pui-react-tools/assets/entry-loader.js?name=index.html!./app/components/application.js
Module build failed: ReferenceError: FEATURE_FLAGS is not defined
    at /Users/pivotal/workspace/project-name/app/components/pretty_cool_feature.js:11:8
    at Object.<anonymous> (/Users/pivotal/workspace/project-name/app/components/pretty_cool_feature:72:18)
    at Module._compile (module.js:571:32)
    at loader (/Users/pivotal/workspace/project-name/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/project-name/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
 @ ./app/bootstrap.js 24:4-97
Child extract-text-webpack-plugin:
```

**Comment by atomanyih** [comment]
our solution is to do the if within the component but it would be nice to be able to write stuff like that^

**Comment by atomanyih** [comment]
actually it looks like adding

```js
global.FEATURE_FLAGS = {};
```

at an earlier point solves this. I'm unsure why we have to do this but `process.env` is fine

**Comment by charleshansen** [comment]
Weird, I'm not sure exactly why that is necessary. 

The usual problem with the entry-loader is that it runs it's own compile step, but uses a more basically configured webpack than a full webpack compile (otherwise there is a circular run loop). This means that sometimes plugins don't work in the entry-loader. I can't say why you'd get particular error though.

**Comment by charleshansen** [comment]
entry-loader is not used in version 3, if you are still on this, you can give that a whirl
