### ISSUE TITLE
`gulp spec-server` breaks when trying to use gulp-process-env

### ISSUE THREAD

**Issue by wendorf** [pivotal-cf/pui-react-tools#32]
I'm running it through pivotal-cf/react-starter, but I can replicate the issue in a separate environment. This is using pui-react-tools 2.0.3.

```
>> git clone https://github.com/pivotal-cf/react-starter
>> cd react-starter/
>> npm install
>> gulp spec-server

[09:08:53] Using gulpfile /private/tmp/react-starter/gulpfile.js
[09:08:53] Starting 'spec-server'...

0 specs, 0 failures
Finished in 0 seconds
/private/tmp/react-starter/node_modules/gulp-process-env/index.js:43
        var env = _privates$get.env;
                               ^

TypeError: Cannot read property 'env' of undefined
    at DestroyableTransform._flush (/private/tmp/react-starter/node_modules/gulp-process-env/index.js:43:32)
    at DestroyableTransform.<anonymous> (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)
    at prefinish (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:494:12)
    at finishMaybe (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:502:7)
    at endWritable (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:514:3)
    at DestroyableTransform.Writable.end (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:484:41)
    at DestroyableTransform.onend (/private/tmp/react-starter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:499:10)
```

**Comment by charleshansen** [comment]
just checked now, still an issue...
