### ISSUE TITLE
Gulp 4.0.0 can't find assets-config

### ISSUE THREAD

**Issue by dan-ator** [pivotal-cf/pui-react-tools#36]
I am getting this error:
`gulp foreman

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: assets-config
    at getFunction (/Users/dalexander1/Loglio/loglio/node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at map (/Users/dalexander1/Loglio/loglio/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (/Users/dalexander1/Loglio/loglio/node_modules/undertaker/lib/helpers/normalizeArgs.js:22:10)
    at Gulp.series (/Users/dalexander1/Loglio/loglio/node_modules/undertaker/lib/series.js:13:14)
    at Object.<anonymous> (/Users/dalexander1/Loglio/loglio/tasks/server.js:36:21)
    at Module._compile (module.js:413:34)
    at loader (/Users/dalexander1/Loglio/loglio/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dalexander1/Loglio/loglio/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)`

My react tools file looks like this:
`const {Assets, Foreman, Lint, Jasmine} = require('pui-react-tools');
require('../app/components/layout');

Assets.install({
  assets: {
    sass: false,
    html: false
  },
  useAssetsServer: false
});
Foreman.install();
Lint.install();
Jasmine.install();`

**Comment by mingxiao** [comment]
Thanks for filing this issue. We've created a story to track this issue and will prioritize accordingly.

**Comment by dan-ator** [comment]
I will add also, that the error is coming from here `gulp.task('s', gulp.series('server', 'watch-server', 'assets-config'));`

**Comment by dan-ator** [comment]
@mingxiao any update on this one?

**Comment by mingxiao** [comment]
@dan-ator What version of pui-react-tools are you using? If you are using v4.X.X, we've updated the interface to the Assets install https://github.com/pivotal-cf/pui-react-tools/blob/master/README.md#optionswebpack-1

We were successfully able to run `gulp foreman` with that Asset install.
